"""Add TokenUsage table

Revision ID: bca99665f6a0
Revises: e7582e9b9c77
Create Date: 2026-07-10 11:24:29.894450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca99665f6a0'
down_revision: Union[str, Sequence[str], None] = 'e7582e9b9c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_conversation_id'), 'token_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_token_usage_id'), 'token_usage', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_operation_type'), 'token_usage', ['operation_type'], unique=False)
    op.create_index(op.f('ix_token_usage_organization_id'), 'token_usage', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_organization_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_operation_type'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_conversation_id'), table_name='token_usage')
    op.drop_table('token_usage')
    # ### end Alembic commands ###
