"""rename project_id to module

Revision ID: ca1a5537451e
Revises: b20f19142675
Create Date: 2026-07-07 14:30:50.794751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1a5537451e'
down_revision: Union[str, Sequence[str], None] = 'b20f19142675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('module', sa.String(), nullable=True))
    op.drop_column('documents', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'module')
    # ### end Alembic commands ###
