"""add organization table

Revision ID: e7582e9b9c77
Revises: 625c9b53db06
Create Date: 2026-07-09 12:49:57.697607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7582e9b9c77'
down_revision: Union[str, Sequence[str], None] = '625c9b53db06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('token_used', sa.BigInteger(), nullable=False),
    sa.Column('token_limit', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=True)
    
    # Insert any existing organizations from other tables to prevent ForeignKeyViolationError
    op.execute("""
        INSERT INTO organizations (id, org_id, token_used, is_active, created_at, updated_at)
        SELECT gen_random_uuid(), org_id, 0, true, now(), now()
        FROM (
            SELECT organization_id AS org_id FROM conversations WHERE organization_id IS NOT NULL
            UNION
            SELECT organization_id AS org_id FROM documents WHERE organization_id IS NOT NULL
        ) AS existing_orgs
        ON CONFLICT (org_id) DO NOTHING;
    """)

    op.create_foreign_key(None, 'conversations', 'organizations', ['organization_id'], ['org_id'])
    op.create_foreign_key(None, 'documents', 'organizations', ['organization_id'], ['org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
